import type { Metadata } from "next";

import { PrimeReactProvider } from "primereact/api";

import { Inter } from "next/font/google";
import "primereact/resources/themes/bootstrap4-dark-blue/theme.css";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <PrimeReactProvider>
      <html lang="en">
        <body>{children}</body>
      </html>
    </PrimeReactProvider>
  );
}
